name: Setup and Configure Tomcat
on:
 push:
   branches:
     - main
 workflow_dispatch:
jobs:
 setup-tomcat:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Install Dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y wget openjdk-11-jdk
     - name: Download Tomcat
       run: |
         TOMCAT_VERSION=9.0.89
         wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
         sudo mv apache-tomcat-$TOMCAT_VERSION.tar.gz /opt/tomcat
     - name: Set Tomcat Permissions
       run: sudo chmod -R 755 /opt/tomcat
     - name: Configure Tomcat
       run: |
         # Example change: Update port from 8080 to 9090 in server.xml
         sudo sed -i 's/8080/9090/g' /opt/tomcat/conf/server.xml
         # Example change: Add user to tomcat-users.xml
         sudo sed -i '/<\/tomcat-users>/i \  <user username="admin" password="password" roles="manager-gui,admin-gui"/>' /opt/tomcat/conf/tomcat-users.xml
     - name: Restart Tomcat
       run: |
         /opt/tomcat/bin/shutdown.sh
         sleep 5
         /opt/tomcat/bin/startup.sh
     - name: Verify Tomcat Installation
       run: curl -I http://localhost:9090
     - name: Save Logs
       run: |
         cat /opt/tomcat/logs/catalina.out
       continue-on-error: true
